"""Constants for the cloud SessionStart refresh hook."""

PACKAGE_NAME = "claude-dev-env"
MANIFEST_FILE_NAME = ".claude-dev-env-manifest.json"
CLAUDE_HOME_DIRECTORY_NAME = ".claude"
CONFIG_DIR_OVERRIDE_VARIABLE_NAME = "CLAUDE_CONFIG_DIR"
REMOTE_SESSION_VARIABLE_NAME = "CLAUDE_CODE_REMOTE"
REMOTE_SESSION_ACTIVE_VALUE = "true"
REGISTRY_PROBE_TIMEOUT_SECONDS = 30
INSTALL_TIMEOUT_SECONDS = 600
