"""Named imagegen limits and provider settings."""

OPENAI_API_URL = "https://api.openai.com/v1/images/generations"
OPENAI_MODEL = "gpt-image-2"
OPENAI_OUTPUT_FORMAT = "png"
OPENAI_API_KEY_NAME = "OPENAI_API_KEY"
CODEX_TOOL_NAME = "codex-imagegen"
ALL_SUPPORTED_BACKENDS = ("openai-api", "codex-oauth")
ALL_SUPPORTED_RESIZE_POLICIES = ("forbid", "allow")
MAXIMUM_IMAGE_EDGE = 3840
MINIMUM_PIXEL_COUNT = 655_360
MAXIMUM_PIXEL_COUNT = 8_294_400
SIZE_MULTIPLE = 16
JSON_INDENT_LEVEL = 2
MAXIMUM_PROVIDER_BYTES = 64 * 1024 * 1024
CODEX_TIMEOUT_SECONDS = 300
MAXIMUM_CODEX_OUTPUT_BYTES = 1 * 1024 * 1024
OPENAI_TIMEOUT_SECONDS = 120
SIZE_COMPONENT_COUNT = 2
SIZE_SEPARATOR = "x"
PNG_SUFFIX = ".png"
PNG_FORMAT = "PNG"
RECEIPT_SUFFIX = ".json"
TEMPORARY_DIRECTORY_PREFIX = "imagegen-"
TEMPORARY_FILE_TOKEN_BYTES = 8
DEFAULT_PROVIDER_EDGE = 2048
MINIMUM_DIMENSION = 1
MAXIMUM_CODEX_ARTIFACT_COUNT = 1
