"""Constants for execute_split git and gh operations."""

from __future__ import annotations

EXIT_CODE_SUCCESS = 0
EXIT_CODE_FAILURE = 1

PAYLOAD_KEY_ERROR = "error"
PAYLOAD_KEY_DRY_RUN = "dry_run"
PAYLOAD_KEY_CREATED = "created_slices"
PAYLOAD_KEY_PR_URLS = "pr_urls"
PAYLOAD_KEY_SUPERSEDE = "supersede"
PAYLOAD_KEY_FAMILY_TREE = "family_tree"
PAYLOAD_KEY_STACK_LABELS = "stack_labels"
PAYLOAD_KEY_COMMENTED = "commented"
PAYLOAD_KEY_CLOSED = "closed"
PAYLOAD_KEY_LABELED = "labeled"
PAYLOAD_KEY_LABELED_PR_NUMBERS = "labeled_pr_numbers"
PAYLOAD_KEY_LABELS = "labels"
PAYLOAD_KEY_CHILD_PR_NUMBERS = "child_pr_numbers"
PAYLOAD_KEY_COMMENTED_PR_NUMBERS = "commented_pr_numbers"
PAYLOAD_KEY_SKIPPED = "skipped"
PAYLOAD_KEY_SKIP_REASON = "skip_reason"
PAYLOAD_KEY_SUPERSEDE_ERROR = "error"
PAYLOAD_KEY_FAMILY_TREE_ERROR = "error"
PAYLOAD_KEY_STACK_LABELS_ERROR = "error"

GIT_COMMAND = "git"
GIT_FETCH = "fetch"
GIT_CHECKOUT = "checkout"
GIT_BRANCH = "branch"
GIT_ADD = "add"
GIT_COMMIT = "commit"
GIT_PUSH = "push"
GIT_REV_PARSE = "rev-parse"
GIT_SHOW_TOPLEVEL = "--show-toplevel"
GIT_STATUS = "status"
GIT_PORCELAIN = "--porcelain"
GIT_SET_UPSTREAM = "-u"
GIT_MESSAGE_FLAG = "-m"
GIT_ORIGIN = "origin"

GH_COMMAND = "gh"
GH_PR = "pr"
GH_CREATE = "create"
GH_COMMENT = "comment"
GH_CLOSE = "close"
GH_VIEW = "view"
GH_EDIT = "edit"
GH_LABEL = "label"
GH_LABEL_CREATE = "create"
GH_ADD_LABEL = "--add-label"
GH_LABEL_FORCE = "--force"
GH_LABEL_COLOR = "--color"
GH_LABEL_DESCRIPTION = "--description"
GH_DRAFT = "--draft"
GH_TITLE = "--title"
GH_BODY_FILE = "--body-file"
GH_BASE = "--base"
GH_HEAD = "--head"
GH_REPO_FLAG = "--repo"
GH_JSON = "--json"

DEFAULT_COMMIT_MESSAGE_TEMPLATE = "feat: %s\n\n%s\n\nSplit from PR #%s."

ERROR_DIRTY_TREE = "working tree is dirty; commit or stash before execute_split"
ERROR_REPO_NOT_GIT = "path is not inside a git repository: %s"
ERROR_EXECUTE_FAILED = "execute_split failed: %s"
ERROR_BRANCH_EXISTS = "branch already exists: %s"
ERROR_CHECKOUT_FILES = "failed to checkout files from %s: %s"
ERROR_COMMIT_FAILED = "commit failed on %s: %s"
ERROR_PUSH_FAILED = "push failed for %s: %s"
ERROR_PR_CREATE_FAILED = "gh pr create failed for %s: %s"
ERROR_EMPTY_SLICE_AFTER_CHECKOUT = "no files staged for slice %s after checkout"
ERROR_SUPERSEDE_COMMENT_FAILED = "gh pr comment failed for source #%s: %s"
ERROR_SUPERSEDE_CLOSE_FAILED = "gh pr close failed for source #%s: %s"
ERROR_SUPERSEDE_VIEW_FAILED = "gh pr view failed for source #%s: %s"
ERROR_FAMILY_TREE_COMMENT_FAILED = "gh pr comment failed for family tree on #%s: %s"
ERROR_STACK_LABEL_ENSURE_FAILED = "gh label create failed for %s: %s"
ERROR_STACK_LABEL_APPLY_FAILED = "gh pr edit --add-label failed for #%s: %s"
ERROR_COLLECTION_FAILED = (
    "pytest collection failed on slice %s after commit; definitions or imports "
    "are on the wrong side of the cut. Re-bucket the plan so every test path "
    "imports only symbols already present on its stack base. Detail:\n%s"
)

JSON_INDENT_SPACES = 2
NEWLINE = "\n"
PYTEST_MODULE = "pytest"
PYTEST_COLLECT_ONLY_FLAG = "--collect-only"
PYTEST_QUIET_FLAG = "-q"
PYTEST_PATHSPEC = "--"
PYTHON_MODULE_FLAG = "-m"
COLLECTION_TIMEOUT_SECONDS = 120
COLLECTION_SKIP_DISABLED = "collection_check_disabled"
COLLECTION_SKIP_NO_TEST_PATHS = "no_collectable_test_paths"
COLLECTION_SKIP_NO_ON_DISK_TESTS = "no_on_disk_test_paths"
COLLECTION_SKIP_PYTEST_UNAVAILABLE = "pytest_unavailable"
ALL_PYTEST_MISSING_MARKERS = (
    "No module named pytest",
    "No module named 'pytest'",
)
TEST_MODULE_PREFIX = "test_"
TEST_MODULE_SUFFIX = "_test.py"
PYTHON_FILE_SUFFIX = ".py"
CONFTEST_BASENAME = "conftest.py"
PAYLOAD_KEY_COLLECTION = "collection"
PAYLOAD_KEY_CHECKED = "checked"
PAYLOAD_KEY_PASSED = "passed"
PAYLOAD_KEY_TEST_PATHS = "test_paths"
PAYLOAD_KEY_COLLECTION_ERROR = "error"
GIT_REFS_REMOTES_PREFIX = "refs/remotes/"
GIT_REFS_HEADS_PREFIX = "refs/heads/"
MARKDOWN_BODY_SUFFIX = ".md"
GIT_CHECKOUT_FORCE_CREATE = "-B"
GIT_ADD_PATHSPEC = "--"
PAYLOAD_KEY_PARTIAL = "partial"
PAYLOAD_KEY_FAILED_SLICE = "failed_slice"

MINIMUM_SLICES_FOR_SUPERSEDE = 2
PR_URL_NUMBER_MARKER = "/pull/"
SUPERSEDE_HEADING = "## Superseded by stacked split"
SUPERSEDE_INTRO = (
    "This PR was file-split into a stacked draft chain. Review and merge the "
    "stack; this source PR is closed as superseded."
)
SUPERSEDE_MERGE_ORDER_LABEL = "**Merge order:**"
SUPERSEDE_MERGE_ORDER_SEPARATOR = " → "
SUPERSEDE_PR_HASH_PREFIX = "#"
SUPERSEDE_LIST_ITEM_TEMPLATE = "%s. #%s — %s"
SUPERSEDE_SKIP_ATOMIC = "atomic_single_slice"
SUPERSEDE_SKIP_NO_CHILD_URLS = "no_child_pr_urls"
SUPERSEDE_SKIP_PARTIAL = "partial_stack"
SUPERSEDE_SKIP_CREATE_PRS_OFF = "create_prs_disabled"
SUPERSEDE_SKIP_ALREADY_DONE = "already_superseded"
SUPERSEDE_SKIP_DISABLED = "supersede_disabled"
FAMILY_TREE_HEADING = "## Split family tree"
FAMILY_TREE_SOURCE_LABEL = "**Source:**"
FAMILY_TREE_MERGE_ORDER_LABEL = "**Merge order:**"
FAMILY_TREE_LIST_ITEM_TEMPLATE = "%s. #%s — %s"
FAMILY_TREE_LIST_ITEM_THIS_TEMPLATE = "%s. #%s — %s ← **this PR**"
FAMILY_TREE_POSITION_TEMPLATE = "This PR is **#%s** (position %s of %s)."
FAMILY_TREE_MERGE_HINT = "Merge earlier slices first. Review and merge in order."
FAMILY_TREE_SKIP_CREATE_PRS_OFF = "create_prs_disabled"
FAMILY_TREE_SKIP_NO_CHILD_URLS = "no_child_pr_urls"
FAMILY_TREE_SKIP_PARTIAL = "partial_stack"
LABEL_SPLIT_PR = "split-pr"
LABEL_STACK_PREFIX = "split-stack:"
LABEL_SPLIT_PR_COLOR = "0E8A16"
LABEL_STACK_COLOR = "1D76DB"
LABEL_SPLIT_PR_DESCRIPTION = "Produced by the split-pr skill (discovery filter)"
LABEL_STACK_DESCRIPTION_TEMPLATE = "Stacked split from source PR #%s"
STACK_LABELS_SKIP_CREATE_PRS_OFF = FAMILY_TREE_SKIP_CREATE_PRS_OFF
STACK_LABELS_SKIP_NO_CHILD_URLS = FAMILY_TREE_SKIP_NO_CHILD_URLS
STACK_LABELS_SKIP_PARTIAL = FAMILY_TREE_SKIP_PARTIAL
GH_STATE_FIELD = "state"
GH_COMMENTS_FIELD = "comments"
GH_COMMENT_BODY_FIELD = "body"
GH_STATE_CLOSED = "CLOSED"
GH_VIEW_FIELDS = "state,comments"

