"""Version and shared literals for Cursor rule sync."""

GENERATOR_VERSION = "1.2.3"

CANONICAL_DOC_FILES: tuple[str, ...] = ("CODE_RULES.md", "TEST_QUALITY.md")
MAX_RULE_BODY_LINES = 50
TEST_GLOBS = "**/*.test.*,**/*.spec.*,**/test_*,**/*_test.*"
CODE_RULES_POINTER_FALLBACK = (
    "_(Full code-quality rules: `~/.claude/system-prompts/software-engineer.xml`"
    " under `<code_quality>`.)_"
)

HEADER = """<!-- Generated by sync-to-cursor.py — do not edit directly -->
<!-- Re-run: python ~/.claude/scripts/sync-to-cursor.py -->
<!-- Output: .cursor/rules/*.mdc, .cursor/docs/*.md (see LLM_SETTINGS_ROOT in script docstring) -->
"""
