"""Relative paths for the sync-ai-rules listener."""

BUGBOT_DESTINATION_PATH = ".cursor/BUGBOT.md"
AGENTS_DESTINATION_PATH = "AGENTS.md"
SOURCE_FILE_PATH = AGENTS_DESTINATION_PATH
DESTINATION_PATHS: tuple[str, ...] = (
    AGENTS_DESTINATION_PATH,
    BUGBOT_DESTINATION_PATH,
)
BUGBOT_ONLY_DESTINATION_PATHS: tuple[str, ...] = (BUGBOT_DESTINATION_PATH,)
