"""Relative paths and env keys for the sync-ai-rules listener."""

BUGBOT_DESTINATION_PATH = ".cursor/BUGBOT.md"
AGENTS_DESTINATION_PATH = "AGENTS.md"
SOURCE_FILE_PATH = AGENTS_DESTINATION_PATH
DESTINATION_PATHS: tuple[str, ...] = (
    AGENTS_DESTINATION_PATH,
    BUGBOT_DESTINATION_PATH,
)
BUGBOT_ONLY_DESTINATION_PATHS: tuple[str, ...] = (BUGBOT_DESTINATION_PATH,)
GITHUB_TOKEN_ENV_KEY = "GITHUB_TOKEN"
GITHUB_REPOSITORY_ENV_KEY = "GITHUB_REPOSITORY"
SOURCE_COMMIT_ENV_KEY = "SOURCE_COMMIT"
RAW_URL_ENV_KEY = "RAW_URL"
FORCE_INITIAL_OVERWRITE_ENV_KEY = "FORCE_INITIAL_OVERWRITE"
