"""Shared environment variable names for the MSYS path-conversion rewriter."""

from __future__ import annotations

__all__ = [
    "ALL_MSYS_PATH_CONVERSION_VARIABLE_NAMES",
    "MSYS_PATH_CONVERSION_VARIABLE_NAME",
    "MSYS_ARGUMENT_CONVERSION_EXCLUSION_VARIABLE_NAME",
]

MSYS_PATH_CONVERSION_VARIABLE_NAME: str = "MSYS_NO_PATHCONV"
MSYS_ARGUMENT_CONVERSION_EXCLUSION_VARIABLE_NAME: str = "MSYS2_ARG_CONV_EXCL"
ALL_MSYS_PATH_CONVERSION_VARIABLE_NAMES: tuple[str, ...] = (
    MSYS_PATH_CONVERSION_VARIABLE_NAME,
    MSYS_ARGUMENT_CONVERSION_EXCLUSION_VARIABLE_NAME,
)
