"""Configuration constants for the plain_language_blocker PreToolUse hook."""

from __future__ import annotations

import re

REPLACEMENT_BY_TERM: dict[str, str] = {
    "addressees are requested": "(omit), please",
    "under the provisions of": "under",
    "interpose no objection": "don't object",
    "afford an opportunity": "allow, let",
    "has a requirement for": "needs",
    "is in consonance with": "agrees with, follows",
    "not later than 10 may": "by 10 May, before 11 May",
    "provides guidance for": "guides",
    "successfully complete": "complete, pass",
    "with the exception of": "except for",
    "due to the fact that": "due to, since",
    "effect modifications": "make changes",
    "in view of the above": "so",
    "adversely impact on": "hurt, set back",
    "at the present time": "at present, now",
    "not later than 1600": "by 1600",
    "combat environment": "combat",
    "in a timely manner": "on time, promptly",
    "in accordance with": "by, following, per, under",
    "in the near future": "shortly, soon",
    "is responsible for": "(omit) handles",
    "on a regular basis": "(omit)",
    "until such time as": "until",
    "during the period": "during",
    "in the process of": "(omit)",
    "with reference to": "about",
    "as prescribed by": "in, under",
    "in the amount of": "for",
    "is applicable to": "applies to",
    "is authorized to": "may",
    "state-of-the-art": "latest",
    "close proximity": "near",
    "for a period of": "for",
    "in an effort to": "to",
    "in the event of": "if",
    "it is essential": "must, need to",
    "it is requested": "please, we request, I request",
    "notwithstanding": "inspite of, still",
    "the undersigned": "I",
    "arrive onboard": "arrive",
    "in relation to": "about, with, to",
    "incumbent upon": "must",
    "limited number": "limits",
    "take action to": "(omit)",
    "as a means of": "to",
    "in order that": "for, so",
    "pertaining to": "about, of, on",
    "provided that": "if",
    "this activity": "us, we",
    "advantageous": "helpful",
    "consequently": "so",
    "in regard to": "about, concerning, on",
    "remuneration": "pay, payment",
    "set forth in": "in",
    "subsequently": "after, later, then",
    "the month of": "(omit)",
    "a number of": "some",
    "accordingly": "so",
    "adjacent to": "next to",
    "appreciable": "many",
    "appropriate": "(omit), proper, right",
    "approximate": "about",
    "by means of": "by, with",
    "comply with": "follow",
    "consolidate": "combine, join, merge",
    "constitutes": "is, forms, makes up",
    "demonstrate": "prove, show",
    "discontinue": "drop, stop",
    "disseminate": "give, issue, pass, send",
    "expeditious": "fast, quick",
    "immediately": "at once",
    "in addition": "also, besides, too",
    "in order to": "to",
    "inasmuch as": "since",
    "methodology": "method",
    "necessitate": "cause, need",
    "participate": "take part",
    "practicable": "practical",
    "proficiency": "skill",
    "pursuant to": "by, following, per, under",
    "relative to": "about, on",
    "requirement": "need",
    "substantial": "large, much",
    "time period": "(either one)",
    "utilization": "use",
    "your office": "you",
    "a and/or b": "a or b or both",
    "accomplish": "carry out, do",
    "additional": "added, more, other",
    "addressees": "you",
    "anticipate": "expect",
    "assistance": "aid, help",
    "be advised": "(omit)",
    "capability": "ability",
    "concerning": "about, on",
    "equipments": "equipment",
    "expiration": "end",
    "facilitate": "ease, help",
    "frequently": "often",
    "heretofore": "until now",
    "in lieu of": "instead",
    "in view of": "since",
    "indication": "sign",
    "inter alia": "(omit)",
    "it appears": "seems",
    "parameters": "limits",
    "previously": "before",
    "prioritize": "rank",
    "promulgate": "issue, publish",
    "represents": "is",
    "similar to": "like",
    "subsequent": "later, next",
    "sufficient": "enough",
    "the use of": "(omit)",
    "accompany": "go with",
    "ascertain": "find out, learn",
    "component": "part",
    "currently": "(omit), now",
    "designate": "appoint, choose, name",
    "determine": "decide, figure, find",
    "eliminate": "cut, drop, end",
    "encounter": "meet",
    "enumerate": "count",
    "equitable": "fair",
    "establish": "set up, prove, show",
    "evidenced": "showed",
    "expertise": "ability",
    "failed to": "didn't",
    "identical": "same",
    "implement": "carry out, start",
    "inception": "start",
    "interface": "meet, work with",
    "magnitude": "size",
    "objective": "aim, goal",
    "regarding": "about, of, on",
    "remainder": "rest",
    "selection": "choice",
    "terminate": "end, stop",
    "there are": "(omit)",
    "therefore": "so",
    "witnessed": "saw",
    "accorded": "given",
    "accurate": "correct, exact, right",
    "aircraft": "plane",
    "allocate": "divide",
    "apparent": "clear, plain",
    "combined": "joint",
    "commence": "begin, start",
    "comprise": "form, include, make up",
    "contains": "has",
    "disclose": "show",
    "endeavor": "try",
    "expedite": "hasten, speed up",
    "feasible": "can be done, workable",
    "finalize": "complete, finish",
    "function": "act, role, work",
    "herewith": "below, here",
    "identify": "find, name, show",
    "impacted": "affected, changed",
    "indicate": "show, write down",
    "initiate": "start",
    "maintain": "keep, support",
    "minimize": "decrease, method",
    "numerous": "many",
    "obligate": "bind, compel",
    "preclude": "prevent",
    "previous": "earlier",
    "prior to": "before",
    "purchase": "buy",
    "relocate": "move",
    "there is": "(omit)",
    "transmit": "send",
    "validate": "confirm",
    "address": "discuss",
    "attempt": "try",
    "benefit": "help",
    "command": "us, we",
    "convene": "meet",
    "evident": "clear",
    "exhibit": "show",
    "females": "women",
    "forfeit": "give up, lose",
    "forward": "send",
    "furnish": "give, send",
    "however": "but",
    "initial": "first",
    "liaison": "discussion",
    "maximum": "greatest, largest, most",
    "minimum": "least, smallest",
    "monitor": "check, watch",
    "observe": "see",
    "operate": "run, use, work",
    "optimum": "best, greatest, most",
    "perform": "do",
    "portion": "part",
    "possess": "have, own",
    "proceed": "do, go ahead, try",
    "procure": "(omit)",
    "provide": "give, offer, say",
    "reflect": "say, show",
    "request": "ask",
    "require": "must, need",
    "solicit": "ask for, request",
    "subject": "the, this, your",
    "therein": "there",
    "thereof": "its, their",
    "utilize": "use",
    "warrant": "call for, permit",
    "whereas": "because, since",
    "accrue": "add, gain",
    "advise": "recommend, tell",
    "assist": "aid, help",
    "attain": "meet",
    "caveat": "warning",
    "delete": "cut, drop",
    "depart": "leave",
    "desire": "want, wish",
    "employ": "use",
    "ensure": "make sure",
    "expend": "spend",
    "herein": "here",
    "modify": "change",
    "notify": "let know, tell",
    "option": "choice, way",
    "permit": "let",
    "remain": "stay",
    "render": "give, make",
    "reside": "live",
    "retain": "keep",
    "submit": "give, send",
    "timely": "prompt",
    "viable": "practical, workable",
    "elect": "choose, pick",
    "it is": "(omit)",
    "deem": "believe, consider, think",
    "said": "the, this, that",
    "same": "the, this, that",
    "such": "the, this, that",
    "type": "(omit)",
    "vice": "instead of, versus",
}

ALL_TERM_PATTERNS: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"\b" + re.escape(each_term) + r"\b", re.IGNORECASE), each_replacement)
    for each_term, each_replacement in REPLACEMENT_BY_TERM.items()
]

ALL_SOFTWARE_TERMS: frozenset[str] = frozenset(
    {
        "command",
        "function",
        "address",
        "parameters",
        "interface",
        "component",
        "monitor",
        "request",
        "validate",
        "however",
        "forward",
        "subject",
        "same",
        "such",
        "said",
        "type",
        "it is",
        "there is",
        "there are",
    }
)

FENCED_CODE_BLOCK_PATTERN: re.Pattern[str] = re.compile(r"```[\s\S]*?```", re.MULTILINE)
INLINE_CODE_PATTERN: re.Pattern[str] = re.compile(r"`[^`]+`")
BLOCKQUOTE_LINE_PATTERN: re.Pattern[str] = re.compile(r"^\s*>.*$", re.MULTILINE)
URL_PATTERN: re.Pattern[str] = re.compile(r"https?://\S+", re.IGNORECASE)
FILE_PATH_PATTERN: re.Pattern[str] = re.compile(
    r"(?<![\w/\\])(?:[A-Za-z]:[\\/]|~?[\\/]|\.{1,2}[\\/])(?:[\w.\-]+[\\/])*[\w.\-]+"
    r"|(?:[\w.\-]+[\\/])+[\w.\-]+\.[A-Za-z0-9]+"
)

MARKDOWN_EXTENSION: str = ".md"
ASK_USER_QUESTION_TOOL_NAME: str = "AskUserQuestion"
ALL_WRITE_EDIT_TOOL_NAMES: frozenset[str] = frozenset({"Write", "Edit", "MultiEdit"})

USER_FACING_PLAIN_LANGUAGE_NOTICE: str = (
    "Plain-language check: replace each flagged formal word with the simpler "
    "word named in the reason."
)
