"""Constants for the changed-surface refactor advisory."""

from __future__ import annotations

GIT_EXECUTABLE_TOKEN: str = "git"
GIT_COMMAND_TIMEOUT_SECONDS: int = 5
MAXIMUM_REFACTOR_LINE_DELTA: int = 3
REFACTOR_LINE_DELTA_DIVISOR: int = 2
CHANGED_SURFACE_MATCH_RATIO: float = 0.5
ALL_PYTHON_KEYWORDS: frozenset[str] = frozenset(
    {
        "def",
        "class",
        "return",
        "import",
        "from",
        "if",
        "elif",
        "else",
        "for",
        "while",
        "try",
        "except",
        "finally",
        "with",
        "as",
        "yield",
        "raise",
        "pass",
        "break",
        "continue",
        "and",
        "or",
        "not",
        "in",
        "is",
        "lambda",
        "None",
        "True",
        "False",
        "self",
        "cls",
        "async",
        "await",
        "global",
        "nonlocal",
        "assert",
        "del",
        "print",
        "len",
        "range",
        "list",
        "dict",
        "set",
        "str",
        "int",
        "float",
        "bool",
        "type",
        "isinstance",
        "hasattr",
        "getattr",
        "setattr",
        "super",
        "property",
        "staticmethod",
        "classmethod",
        "abstractmethod",
        "Optional",
        "Union",
        "List",
        "Dict",
        "Set",
        "Tuple",
        "Any",
    }
)
