"""Configuration constants for the shared hidden-console creation flags."""

WINDOWS_PLATFORM: str = "win32"
CREATE_NO_WINDOW_ATTRIBUTE: str = "CREATE_NO_WINDOW"
CREATE_NEW_PROCESS_GROUP_ATTRIBUTE: str = "CREATE_NEW_PROCESS_GROUP"
STARTUP_INFO_ATTRIBUTE: str = "STARTUPINFO"
SHOW_WINDOW_FLAG_ATTRIBUTE: str = "STARTF_USESHOWWINDOW"
HIDE_WINDOW_COMMAND_ATTRIBUTE: str = "SW_HIDE"
NO_CREATION_FLAGS: int = 0
