#!/usr/bin/env python3
"""Generate Cursor rules from ~/.claude/rules and docs.

Writes to <profile or repo>/.cursor/rules/*.mdc, .cursor/docs/*.md (byte copies of
CODE_RULES.md and TEST_QUALITY.md when present), and .cursor/.sync-manifest.json.
If LLM_SETTINGS_ROOT is set to the llm-settings repo root, uses <root>/.claude and
<root>/.cursor. Otherwise uses ~/.claude and ~/.cursor (after junction install).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Literal

GENERATOR_VERSION = "1.2.2"

CANONICAL_DOC_FILES: tuple[str, ...] = ("CODE_RULES.md", "TEST_QUALITY.md")
MAX_RULE_BODY_LINES = 50
TEST_GLOBS = "**/*.test.*,**/*.spec.*,**/test_*,**/*_test.*"

HEADER = """<!-- Generated by sync-to-cursor.py — do not edit directly -->
<!-- Re-run: python ~/.claude/scripts/sync-to-cursor.py -->
<!-- Output: .cursor/rules/*.mdc, .cursor/docs/*.md (see LLM_SETTINGS_ROOT in script docstring) -->
"""


def _llm_layout_paths() -> tuple[Path, Path, Path, Path]:
    """Return (claude_dir, cursor_dir, rules_out_dir, manifest_path)."""
    raw = os.environ.get("LLM_SETTINGS_ROOT", "").strip()
    if raw:
        base = Path(raw).expanduser().resolve()
        claude = base / ".claude"
        cursor = base / ".cursor"
    else:
        home = Path.home()
        claude = home / ".claude"
        cursor = home / ".cursor"
    return claude, cursor, cursor / "rules", cursor / ".sync-manifest.json"


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _sync_canonical_docs(
    claude: Path,
    cursor: Path,
    dry_run: bool,
    quiet: bool,
) -> dict:
    docs_out = cursor / "docs"
    if not dry_run:
        docs_out.mkdir(parents=True, exist_ok=True)
    new_docs: dict = {}
    for name in CANONICAL_DOC_FILES:
        src = claude / "docs" / name
        if not src.is_file():
            if not quiet:
                print(f"WARN     docs/{name} (missing source: {src})")
            continue
        dst = docs_out / name
        key = f"docs/{name}"
        src_hash = _sha256_bytes(src.read_bytes())
        if dry_run:
            if dst.is_file():
                out_hash = _sha256_bytes(dst.read_bytes())
            else:
                out_hash = ""
        else:
            shutil.copy2(src, dst)
            out_hash = _sha256_bytes(dst.read_bytes())
        new_docs[key] = {"sources_hash": src_hash, "output_hash": out_hash}
    return new_docs


def _check_canonical_docs(claude: Path, cursor: Path, docs_entries: dict) -> bool:
    for name in CANONICAL_DOC_FILES:
        key = f"docs/{name}"
        src = claude / "docs" / name
        dst = cursor / "docs" / name
        if not src.is_file():
            if key in docs_entries:
                return False
            continue
        if not dst.is_file():
            return False
        src_hash = _sha256_bytes(src.read_bytes())
        dst_hash = _sha256_bytes(dst.read_bytes())
        prev = docs_entries.get(key)
        if not prev:
            return False
        if prev.get("sources_hash") != src_hash:
            return False
        if prev.get("output_hash") != dst_hash:
            return False
    return True


def _parse_h2_sections(md: str) -> dict[str, str]:
    parts = re.split(r"^## ", md, flags=re.MULTILINE)
    sections: dict[str, str] = {}
    for part in parts[1:]:
        title_line, _, body = part.partition("\n")
        sections[title_line.strip()] = body.strip()
    return sections


def _filter_core_principles(body: str) -> str:
    lines = []
    for line in body.splitlines():
        if "readability-review" in line or "readability standard" in line:
            continue
        lines.append(line)
    return "\n".join(lines).strip()


def _limit_lines(text: str, max_lines: int) -> str:
    lines = text.splitlines()
    if len(lines) <= max_lines:
        return text
    return (
        "\n".join(lines[:max_lines])
        + "\n\n_(Truncated for Cursor rule length; see the synced reference in `.cursor/docs/` "
        "(`CODE_RULES.md` or `TEST_QUALITY.md` as applicable) and follow its canonical source "
        "under `~/.claude/docs` when needed.)_"
    )


def _strip_code_standards_blockquote(md: str) -> str:
    lines = md.splitlines()
    out: list[str] = []
    i = 0
    while i < len(lines):
        if lines[i].startswith(">") and "MANDATORY REFERENCE" in lines[i]:
            while i < len(lines) and lines[i].startswith(">"):
                i += 1
            while i < len(lines) and lines[i].strip() == "":
                i += 1
            continue
        out.append(lines[i])
        i += 1
    return "\n".join(out).strip()


def merge_code_standards(sources: tuple[Path, ...]) -> str:
    code_standards_markdown = _strip_code_standards_blockquote(
        sources[0].read_text(encoding="utf-8")
    )
    code_standards_markdown = "\n".join(
        ln for ln in code_standards_markdown.splitlines() if not ln.strip().startswith("- TDD ")
    )
    code_rules_markdown = sources[1].read_text(encoding="utf-8")
    sections_by_heading = _parse_h2_sections(code_rules_markdown)
    include_order = [
        "COMMENT PRESERVATION (ABSOLUTE RULE)",
        "CORE PRINCIPLES",
        "⚡ HOOK-ENFORCED RULES",
        "4. CONFIG LOCATIONS",
        "5. NO ABBREVIATIONS",
        "6. COMPLETE TYPE HINTS",
        "9. SELF-CONTAINED COMPONENTS",
    ]
    chunks = [
        code_standards_markdown,
        "",
        "## Reference (full text: `.cursor/docs/CODE_RULES.md`)",
    ]
    for title in include_order:
        body = sections_by_heading.get(title, "")
        if title == "CORE PRINCIPLES":
            body = _filter_core_principles(body)
        if body:
            chunks.append(f"## {title}\n\n{body}")
    merged = "\n\n".join(chunks)
    return _limit_lines(merged, MAX_RULE_BODY_LINES)


def merge_test_quality(sources: tuple[Path, ...]) -> str:
    testing = sources[0].read_text(encoding="utf-8").strip()
    test_quality_markdown = sources[1].read_text(encoding="utf-8")
    sections_by_heading = _parse_h2_sections(test_quality_markdown)
    include_order = [
        "Delete Useless Tests",
        "Test Dependencies MUST FAIL",
        "Core Testing Principles",
        "React Testing Patterns",
        "Test File Organization",
    ]
    chunks = [testing, "", "## Reference (full text: `.cursor/docs/TEST_QUALITY.md`)"]
    for title in include_order:
        body = sections_by_heading.get(title, "")
        if body:
            chunks.append(f"## {title}\n\n{body}")
    merged = "\n\n".join(chunks)
    return _limit_lines(merged, MAX_RULE_BODY_LINES)


def strip_anthropic_refs(text: str) -> str:
    out_lines: list[str] = []
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("Source:") and (
            "anthropic" in s.lower()
            or "claude.com" in s.lower()
            or "docs.anthropic" in s.lower()
        ):
            continue
        if "docs.anthropic.com" in line:
            continue
        out_lines.append(line)
    text = "\n".join(out_lines)
    text = re.sub(
        r"<do_not_act_before_instructions>\s*",
        "",
        text,
        flags=re.DOTALL,
    )
    text = re.sub(r"\s*</do_not_act_before_instructions>", "", text)
    return text.strip()


def verbatim(text: str) -> str:
    return text.strip()


def near_verbatim(text: str) -> str:
    return strip_anthropic_refs(text)


def strip_leading_yaml_frontmatter(text: str) -> str:
    """Remove leading `---` ... `---` block (e.g. Claude `paths:`) so Cursor `.mdc` uses its own frontmatter."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return text
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            return "\n".join(lines[i + 1 :]).lstrip("\n")
    return text


TransformName = Literal["verbatim", "near_verbatim", "merge_code_standards", "merge_test_quality"]


def apply_transform(
    name: TransformName,
    sources: tuple[Path, ...],
    *,
    strip_leading_frontmatter: bool = False,
) -> str:
    if name == "merge_code_standards":
        return merge_code_standards(sources)
    if name == "merge_test_quality":
        return merge_test_quality(sources)
    raw = "\n\n".join(p.read_text(encoding="utf-8") for p in sources)
    if strip_leading_frontmatter:
        raw = strip_leading_yaml_frontmatter(raw)
    if name == "verbatim":
        return verbatim(raw)
    if name == "near_verbatim":
        return near_verbatim(raw)
    raise AssertionError(name)


@dataclass(frozen=True)
class RuleMapping:
    key: str
    sources: tuple[Path, ...]
    output_name: str
    always_apply: bool
    globs: str | None
    description: str
    transform: TransformName
    strip_leading_frontmatter: bool = False


def _frontmatter(desc: str, always_apply: bool, globs: str | None) -> str:
    lines = ["---", f"description: {desc}"]
    if globs:
        lines.append(f"globs: {globs}")
    lines.append(f"alwaysApply: {'true' if always_apply else 'false'}")
    lines.append("---")
    return "\n".join(lines) + "\n"


def _full_mdc(mapping: RuleMapping, body: str) -> str:
    return _frontmatter(mapping.description, mapping.always_apply, mapping.globs) + "\n" + HEADER + "\n" + body + "\n"


def build_mappings(claude: Path) -> tuple[RuleMapping, ...]:
    rules_directory = claude / "rules"
    docs_directory = claude / "docs"
    return (
        RuleMapping(
            "code-standards",
            (rules_directory / "code-standards.md", docs_directory / "CODE_RULES.md"),
            "code-standards.mdc",
            True,
            None,
            "Core code standards: naming, types, config, hook-enforced rules",
            "merge_code_standards",
        ),
        RuleMapping(
            "tasklings-preferences",
            (rules_directory / "tasklings-preferences.md",),
            "tasklings-preferences.mdc",
            False,
            r"Y:/Craft a Tale/Behavioral App/Project/**",
            "Tasklings: Prefer / Do / Always engineering preferences (scoped path)",
            "verbatim",
            True,
        ),
        RuleMapping(
            "right-sized-engineering",
            (rules_directory / "right-sized-engineering.md",),
            "right-sized-engineering.mdc",
            True,
            None,
            "Right-sized engineering and complexity budget",
            "verbatim",
        ),
        RuleMapping(
            "bdd",
            (rules_directory / "bdd.md",),
            "bdd.mdc",
            True,
            None,
            "BDD: discovery-driven protocol (outside-in; Illustrate→Formulate→Automate)",
            "verbatim",
        ),
        RuleMapping(
            "test-quality",
            (rules_directory / "testing.md", docs_directory / "TEST_QUALITY.md"),
            "test-quality.mdc",
            False,
            TEST_GLOBS,
            "Testing quality for test files",
            "merge_test_quality",
        ),
        RuleMapping(
            "research-mode",
            (rules_directory / "research-mode.md",),
            "research-mode.mdc",
            True,
            None,
            "Research mode: citations and I don't know",
            "near_verbatim",
        ),
        RuleMapping(
            "conservative-action",
            (rules_directory / "conservative-action.md",),
            "conservative-action.mdc",
            True,
            None,
            "Prefer research over action when intent is unclear",
            "near_verbatim",
        ),
        RuleMapping(
            "explore-thoroughly",
            (rules_directory / "explore-thoroughly.md",),
            "explore-thoroughly.mdc",
            True,
            None,
            "Explore codebase before committing to an approach",
            "near_verbatim",
        ),
    )


def main() -> int:
    ap = argparse.ArgumentParser(description="Sync Claude rules to Cursor .mdc files")
    ap.add_argument("--force", action="store_true", help="Regenerate all outputs")
    ap.add_argument("--dry-run", action="store_true", help="Print actions only")
    ap.add_argument("--check", action="store_true", help="Exit 1 if anything stale")
    ap.add_argument("--quiet", action="store_true", help="Minimal output when up to date")
    args = ap.parse_args()

    claude, cursor, out_dir, manifest_path = _llm_layout_paths()

    mappings = build_mappings(claude)
    old_manifest: dict = {}
    if manifest_path.is_file():
        try:
            old_manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            old_manifest = {}

    entries_meta: dict = old_manifest.get("entries", {})
    docs_entries_meta: dict = old_manifest.get("docs_entries", {})

    def sources_hash(paths: tuple[Path, ...]) -> str:
        return _sha256_bytes(b"\x00".join(p.read_bytes() for p in paths))

    if args.check:
        for m in mappings:
            key = f"rules/{m.output_name}"
            out_path = out_dir / m.output_name
            missing = [p for p in m.sources if not p.is_file()]
            if missing:
                return 1
            src_hash = sources_hash(m.sources)
            prev = entries_meta.get(key, {})
            if src_hash != prev.get("sources_hash"):
                return 1
            prev_out = prev.get("output_hash", "")
            if out_path.is_file() and prev_out:
                if _sha256_bytes(out_path.read_bytes()) != prev_out:
                    return 1
            elif not out_path.is_file():
                return 1
        if out_dir.is_dir():
            for p in out_dir.glob("*.mdc"):
                if p.name not in {x.output_name for x in mappings}:
                    return 1
        if not _check_canonical_docs(claude, cursor, docs_entries_meta):
            return 1
        return 0

    summary = {"skip": 0, "update": 0, "tampered": 0, "warn": 0, "orphan": 0}
    stale_check = False
    new_entries: dict = {}

    out_dir.mkdir(parents=True, exist_ok=True)
    write_allowed = not args.dry_run

    new_docs_entries = _sync_canonical_docs(claude, cursor, args.dry_run, args.quiet)

    for m in mappings:
        key = f"rules/{m.output_name}"
        out_path = out_dir / m.output_name
        missing = [p for p in m.sources if not p.is_file()]
        if missing:
            summary["warn"] += 1
            stale_check = True
            if not args.quiet:
                print(f"WARN     rules/{m.output_name} (missing source: {missing})")
            continue

        src_hash = sources_hash(m.sources)
        prev = entries_meta.get(key, {})
        prev_src = prev.get("sources_hash", "")
        prev_out = prev.get("output_hash", "")

        if (
            not args.force
            and out_path.is_file()
            and prev_src == src_hash
            and prev_out
            and _sha256_bytes(out_path.read_bytes()) == prev_out
        ):
            summary["skip"] += 1
            new_entries[key] = {"sources_hash": src_hash, "output_hash": prev_out}
            continue

        if (
            not args.force
            and out_path.is_file()
            and prev_src == src_hash
            and prev_out
            and _sha256_bytes(out_path.read_bytes()) != prev_out
        ):
            summary["tampered"] += 1
            stale_check = True
            if not args.quiet:
                print(f"TAMPERED rules/{m.output_name} (manual edit; regenerating)")

        stale_check = True
        summary["update"] += 1
        if not args.quiet:
            print(f"UPDATE   rules/{m.output_name}")

        body = apply_transform(
            m.transform,
            m.sources,
            strip_leading_frontmatter=m.strip_leading_frontmatter,
        )
        full = _full_mdc(m, body)
        out_hash = _sha256_bytes(full.encode("utf-8"))
        new_entries[key] = {"sources_hash": src_hash, "output_hash": out_hash}

        if write_allowed:
            out_path.write_text(full, encoding="utf-8", newline="\n")

    expected = {m.output_name for m in mappings}
    for p in out_dir.glob("*.mdc"):
        if p.name not in expected:
            summary["orphan"] += 1
            stale_check = True
            if not args.quiet:
                print(f"WARN     {p.relative_to(cursor)} (orphan — not generated by this tool)")

    manifest_out = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "generator_version": GENERATOR_VERSION,
        "entries": new_entries,
        "docs_entries": new_docs_entries,
    }
    if write_allowed:
        manifest_path.write_text(json.dumps(manifest_out, indent=2) + "\n", encoding="utf-8")

    if (
        not args.quiet
        and summary["skip"]
        and not any((summary["update"], summary["tampered"], summary["warn"], summary["orphan"]))
    ):
        print(f"SKIP     all {summary['skip']} rule(s) unchanged")

    return 0


if __name__ == "__main__":
    sys.exit(main())
