"""Configuration constants for the reviewer opt-out and opt-in gates."""

from __future__ import annotations

CLAUDE_REVIEWS_DISABLED_ENV_VAR_NAME: str = "CLAUDE_REVIEWS_DISABLED"
CLAUDE_REVIEWS_ENABLED_ENV_VAR_NAME: str = "CLAUDE_REVIEWS_ENABLED"
CLAUDE_REVIEWS_DISABLED_TOKEN_SEPARATOR: str = ","
CLAUDE_REVIEWS_DISABLED_BUGTEAM_TOKEN: str = "bugteam"
CLAUDE_REVIEWS_DISABLED_BUGBOT_TOKEN: str = "bugbot"
CLAUDE_REVIEWS_DISABLED_COPILOT_TOKEN: str = "copilot"
CLAUDE_REVIEWS_DISABLED_CODEX_TOKEN: str = "codex"
EXIT_CODE_BUGTEAM_DISABLED_VIA_ENV: int = 7
